TheGirlCode/TheGirlCode/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    #Admin
    url(r'^admin/', admin.site.urls),

    #Home Page
    url(r'^$', views.home , name ='home'),

    #About Us
    url(r'^aboutus/$', views.about_us , name ='about_us'),

    #Workshops
    url(r'^workshops/$', views.workshops , name ='workshops'),

    # Accounts
    url(r'^account/', include('accounts.urls')),



]

TheGirlCode/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done

app_name='accounts'
urlpatterns = [

    # Profile
    url(r'^profile/$', views.view_profile, name ='profile'),

    # Edit Profile Details
    url(r'^settings/edit/$', views.edit_profile, name ='edit_profile'),

    # Change Password
    url(r'^settings/edit/change_password$', views.change_password, name ='change_password'),

    # Login
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),

    # Logout
    url(r'^logout/$', logout,  {'next_page': '/'}, name='logout'),

    # Register
    url(r'^register/$', views.register, name='register'),

    # Compiler
    url(r'^course/compiler/$', views.compiler, name='compiler'),

    # Curriculum 1
    url(r'^course-1/$', views.course_1, name='course1'),

    # Curriculum 2
    url(r'^course-2/$', views.course_2, name='course2'),

    # Curriculum 3
    url(r'^course-3/$', views.course_3, name='course3'),

    # Curriculum 4
    url(r'^course-4/$', views.course_4, name='course4'),

    # Curriculum 5
    url(r'^course-5/$', views.course_5, name='course5'),

    # Curriculum 6
    url(r'^course-6/$', views.course_6, name='course6'),

    # Curriculum 7
    url(r'^course-7/$', views.course_7, name='course7'),

    # Project 1
    url(r'^project-1/calculator$', views.calc, name='calc'),

    # Project 2
    url(r'^project-2/rps$', views.rps, name='rps'),

    # Project 3
    url(r'^project-3/pyglatin', views.pyglatin, name='pyglatin'),



]

TheGirlCode/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from django.db.models.signals import post_save



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)   # Linking with the default django user model
    progress = models.IntegerField(default=0)  # Progress of the user

    answer_1_1 = models.CharField(max_length=50,default="")
    answer_1_1_check = models.BooleanField(default=False)

    answer_1_2 = models.IntegerField(default=0)
    answer_1_2_check = models.BooleanField(default=False)

    answer_1_3 = models.CharField(max_length=50,default="")
    answer_1_3_check = models.BooleanField(default=False)

    answer_1_4 = models.IntegerField(default=0)
    answer_1_4_check = models.BooleanField(default=False)

    answer_2_1 = models.CharField(max_length=50,default="")
    answer_2_1_check = models.BooleanField(default=False)

    answer_2_2= models.CharField(max_length=50,default="")
    answer_2_2_check = models.BooleanField(default=False)

    answer_2_3 = models.IntegerField(default=0)
    answer_2_3_check = models.BooleanField(default=False)

    answer_2_4 = models.CharField(max_length=50,default="")
    answer_2_4_check = models.BooleanField(default=False)

    answer_2_5 = models.CharField(max_length=50,default="")
    answer_2_5_check = models.BooleanField(default=False)

    answer_3_1 = models.CharField(max_length=50, default="")
    answer_3_1_check = models.BooleanField(default=False)

    answer_3_2 = models.CharField(max_length=50, default="")
    answer_3_2_check = models.BooleanField(default=False)

    answer_4_1 = models.IntegerField(default=0)
    answer_4_1_check = models.BooleanField(default=False)

    answer_4_2 = models.CharField(max_length=50, default="")
    answer_4_2_check = models.BooleanField(default=False)

    answer_4_3 = models.CharField(max_length=50, default="")
    answer_4_3_check = models.BooleanField(default=False)

    answer_5_1 = models.CharField(max_length=50, default="")
    answer_5_1_check = models.BooleanField(default=False)

    answer_6_1 = models.CharField(max_length=50, default="")
    answer_6_1_check = models.BooleanField(default=False)

    answer_6_2 = models.CharField(max_length=50, default="")
    answer_6_2_check = models.BooleanField(default=False)

    answer_6_3 = models.CharField(max_length=50, default="")
    answer_6_3_check = models.BooleanField(default=False)

    answer_7_1 = models.CharField(max_length=50, default="")
    answer_7_1_check = models.BooleanField(default=False)

    answer_7_2 = models.IntegerField(default=0)
    answer_7_2_check = models.BooleanField(default=False)

    def __str__(self):  # Displays names on the admin site
        return self.user.username


def create_profile(sender, **kwargs):  # Linking default User to UserProfile
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

TheGirlCode/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True)  # Valid email is mandatory

    class Meta:  # Description of the form
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):  # Saves the data to the data base
        user = super(RegistrationForm, self ).save(commit=False)
        user.email = self.cleaned_data['email']  # Checks for code that can harm the site in the input box

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):

    class Meta:  # Description of the form
        model = User
        fields = (
            'username',
            'email',
        )


class CourseForm1(forms.ModelForm):
    answer_1_1 = forms.CharField()
    answer_1_2 = forms.IntegerField()
    answer_1_3 = forms.CharField()
    answer_1_4 = forms.IntegerField()

    class Meta:
        model = UserProfile
        fields = ('answer_1_1','answer_1_2', 'answer_1_3', 'answer_1_4', )


class CourseForm2(forms.ModelForm):
    answer_2_1 = forms.CharField()
    answer_2_2 = forms.CharField()
    answer_2_3 = forms.IntegerField()
    answer_2_4 = forms.CharField()
    answer_2_5 = forms.CharField()


    class Meta:
        model = UserProfile
        fields = ('answer_2_1','answer_2_2', 'answer_2_3', 'answer_2_4', 'answer_2_5', )


class CourseForm3(forms.ModelForm):
    answer_3_1 = forms.CharField()
    answer_3_2 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_3_1','answer_3_2', )


class CourseForm4(forms.ModelForm):
    answer_4_1 = forms.IntegerField()
    answer_4_2 = forms.CharField()
    answer_4_3 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_4_1', 'answer_4_2', 'answer_4_3', )


class CourseForm5(forms.ModelForm):
    answer_5_1 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_5_1', )


class CourseForm6(forms.ModelForm):
    answer_6_1 = forms.CharField()
    answer_6_2 = forms.CharField()
    answer_6_3 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_6_1','answer_6_2','answer_6_3',  )


class CourseForm7(forms.ModelForm):
    answer_7_1 = forms.CharField()
    answer_7_2 = forms.IntegerField()

    class Meta:
        model = UserProfile
        fields = ('answer_7_1','answer_7_2',)

TheGirlCode/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from accounts.forms import *
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import UserProfile


def login(request):

    return render(request, 'accounts/login.html')


def register(request):
    if request.method == 'POST':  # when submit button is clicked with the user details
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:login'))

    else:  # GET method, i.e. user is requesting the page
        form = RegistrationForm()

    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required  # Page becomes inaccessible to users which are not logged in
def view_profile(request):

    return render(request, 'accounts/profile.html', {'user': request.user})


@login_required
def edit_profile(request):

    if request.method == 'POST':  # When user is submitting the updated info
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))

    else:  # When the user wants to view the page
        form = EditProfileForm(instance=request.user)

        return render(request, 'accounts/editprofile.html', {'form': form})
    

@login_required
def change_password(request):

    if request.method == 'POST':  # When user is submitting the updated info
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # Doesn't logout the user after pw change
            return redirect(reverse('accounts:profile'))

        else:  # If form is not valid, redirects to the same page
            return redirect(reverse('accounts:change_password'))

    else:
        form = PasswordChangeForm(user=request.user)

        return render(request, 'accounts/changepassword.html', {'form': form})


def compiler(request):
    return render(request, 'accounts/compiler.html')


@login_required
def course_1(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm1(request.POST, instance=profile)
        if form.is_valid():
            ans1 = form.cleaned_data['answer_1_1']
            ans2 = form.cleaned_data['answer_1_2']
            ans3 = form.cleaned_data['answer_1_3']
            ans4 = form.cleaned_data['answer_1_4']

            if ans1 == "Hello World" and profile.answer_1_1_check == False:
                profile.progress += 5
                profile.answer_1_1_check = True
                profile.save()
            form.save()

            if ans2 == 2 and profile.answer_1_2_check == False:
                profile.progress += 5
                profile.answer_1_2_check = True
                profile.save()
            form.save()

            if ans3 == "True" and profile.answer_1_3_check == False:
                profile.progress += 5
                profile.answer_1_3_check = True
                profile.save()
            form.save()

            if ans4 == 1500 and profile.answer_1_4_check == False:
                profile.progress += 5
                profile.answer_1_4_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_1.html', args)

    else:
        form = CourseForm1(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_1.html', args)


def course_2(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm2(request.POST, instance=profile)
        if form.is_valid():
            ans5 = form.cleaned_data['answer_2_1']
            ans6 = form.cleaned_data['answer_2_2']
            ans7 = form.cleaned_data['answer_2_3']
            ans8 = form.cleaned_data['answer_2_4']
            ans9 = form.cleaned_data['answer_2_5']

            if ans5 == "JamandButter" and profile.answer_2_1_check == False:
                profile.progress += 5
                profile.answer_2_1_check = True
                profile.save()
            form.save()

            if ans6 == "actor" and profile.answer_2_2_check == False:
                profile.progress += 5
                profile.answer_2_2_check = True
                profile.save()
            form.save()

            if ans7 == 24 and profile.answer_2_3_check == False:
                profile.progress += 5
                profile.answer_2_3_check = True
                profile.save()
            form.save()

            if ans8 == "lang[1]" and profile.answer_2_4_check == False:
                profile.progress += 5
                profile.answer_2_4_check = True
                profile.save()
            form.save()

            if ans9 == "Hop" and profile.answer_2_5_check == False:
                profile.progress += 5
                profile.answer_2_5_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_2.html', args)

    else:
        form = CourseForm2(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_2.html', args)


def course_3(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm3(request.POST, instance=profile)
        if form.is_valid():
            ans10 = form.cleaned_data['answer_3_1']
            ans11 = form.cleaned_data['answer_3_2']

            if ans10 == "Your party was a success!" and profile.answer_3_1_check == False:
                profile.progress += 5
                profile.answer_3_1_check = True
                profile.save()
            form.save()

            if ans11 == "You are ancient." and profile.answer_3_2_check == False:
                profile.progress += 5
                profile.answer_3_2_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_3.html', args)

    else:
        form = CourseForm3(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_3.html', args)


def course_4(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm4(request.POST, instance=profile)
        if form.is_valid():
            ans12 = form.cleaned_data['answer_4_1']
            ans13 = form.cleaned_data['answer_4_2']
            ans14 = form.cleaned_data['answer_4_3']

            if ans12 == 10 and profile.answer_4_1_check == False:
                profile.progress += 5
                profile.answer_4_1_check = True
                profile.save()
            form.save()

            if ans13 == "1 2 3" and profile.answer_4_2_check == False:
                profile.progress += 5
                profile.answer_4_2_check = True
                profile.save()
            form.save()

            if ans14 == "odd even odd even" and profile.answer_4_3_check == False:
                profile.progress += 5
                profile.answer_4_3_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_4.html', args)

    else:
        form = CourseForm4(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_4.html', args)


def course_5(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm5(request.POST, instance=profile)
        if form.is_valid():
            ans15 = form.cleaned_data['answer_5_1']

            if ans15 == "eve.left(90)" and profile.answer_5_1_check == False:
                profile.progress += 5
                profile.answer_5_1_check = True
                profile.save()
            form.save()


        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_5.html', args)

    else:
        form = CourseForm5(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_5.html', args)


def course_6(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm6(request.POST, instance=profile)
        if form.is_valid():
            ans16 = form.cleaned_data['answer_6_1']
            ans17 = form.cleaned_data['answer_6_2']
            ans18 = form.cleaned_data['answer_6_3']

            if ans16 == "butter" and profile.answer_6_1_check == False:
                profile.progress += 5
                profile.answer_6_1_check = True
                profile.save()
            form.save()

            if ans17 == "toffees chocolate" and profile.answer_6_2_check == False:

TheGirlCode/accounts/templates/accounts/changepassword.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/forms.css' %}" type="text/css">
    <link rel="icon" href="{% static 'TheGirlCode/LandingPage/Images/logo_trans.png' %}">
    <title>Change Password | The Girl Code</title>
</head>
<body>
<div class="container">
    <center>
    <h1> Change Password </h1>
    </center>

     <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <br>
          <button type="submit">Save</button>
      </form>

    <br>
    <a href="{% url 'accounts:profile' %}"> Back to Profile </a>

</div>


</body>
</html>

TheGirlCode/accounts/templates/accounts/compiler.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

<iframe src="https://trinket.io/embed/python3/8423ff952d" width="100%"  frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>
<iframe src="https://trinket.io/embed/python3/8423ff952d?runOption=run" width="100%" height="356" frameborder="0" marginwidth="0" marginheight="0" allowfullscreen></iframe>



</body>
</html>

TheGirlCode/accounts/templates/accounts/editprofile.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">

    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/forms.css' %}" type="text/css">
    <link rel="icon" href="{% static 'TheGirlCode/LandingPage/Images/logo_trans.png' %}">
    <title>Edit Profile | The Girl Code</title>
</head>
<body>
<div class="container">
    <center>
    <h1> Edit Profile </h1>
    </center>

     <form method="POST">
          {% csrf_token %}
          {{ form.as_p }}
          <br>
          <button type="submit">Save</button>
      </form>

    <br>
    <a href="{% url 'accounts:profile' %}"> Back to Profile </a>

</div>


</body>
</html>

TheGirlCode/accounts/templates/accounts/login.html
<!DOCTYPE html>

<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Login | The Girl Code</title>

    <!-- Linking the CSS File -->
    {% load static %}
    <link rel="stylesheet" href="{% static 'accounts/forms.css' %}" type="text/css">
    <link rel="icon" href="{% static 'TheGirlCode/LandingPage/Images/logo_trans.png' %}">

</head>

<body>

<div class="container">
    {% if user.is_authenticated %} <!-- checks if the user is logged in or not  -->
    <h3> Logout before logging in again.</h3>
    <br>
    <center>
        <a href="{% url 'home' %}"> Home </a>
    </center>

    {% else %}

    <center>
        <h1> Login Page </h1>
    </center>
    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}

        <button type="submit">Login</button>
    </form>

    {% endif %}

</div>



</body>
</html>

TheGirlCode/accounts/templates/accounts/profile.html
<!doctype html>
<html lang="en">

  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <meta name="description" content="">
    <meta name="author" content="">

    <title>User Profile | The Girl Code</title>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>

    {% load static %}
    <!-- Bootstrap core CSS -->
    <link href="{% static 'Bootstrap/dist/css/bootstrap.min.css' %}" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="{% static 'accounts/profile/profile.css' %}" rel="stylesheet">
    <link href="{% static 'TheGirlCode/LandingPage/master.css' %}" rel="stylesheet">

    <link rel="icon" href="{% static 'TheGirlCode/LandingPage/Images/logo_trans.png' %}">
  </head>

  <body>
    <!-- header -->
    <header class="navbar-fixed-top light">
      <nav>

        <ul class="leftalign">
          <li><a style="color: rgba(255, 51, 85, .85)" href="{% url 'accounts:profile' %}">
              The Girl Code
             </a></li>
        </ul>

        <ul>
         <li>
             {% if user.userprofile.progress < 20 %}
             <a href="{% url 'accounts:course1' %}"> Course</a>

             {% elif user.userprofile.progress >= 20 and user.userprofile.progress < 45 %}
             <a href="{% url 'accounts:course2' %}"> Course</a>

             {% elif user.userprofile.progress >= 45 and user.userprofile.progress < 55 %}
             <a href="{% url 'accounts:course3' %}"> Course</a>

             {% elif user.userprofile.progress >= 55 and user.userprofile.progress < 70 %}
             <a href="{% url 'accounts:course4' %}"> Course</a>

             {% elif user.userprofile.progress >= 70 and user.userprofile.progress < 75 %}
             <a href="{% url 'accounts:course5' %}"> Course</a>

             {% elif user.userprofile.progress >= 75 and user.userprofile.progress < 90 %}
             <a href="{% url 'accounts:course6' %}"> Course</a>

             {% elif user.userprofile.progress >= 90 and user.userprofile.progress <= 100 %}
             <a href="{% url 'accounts:course7' %}"> Course</a>


             {% endif %}
         </li>
         <li class="dropdown">
            <a style="color: rgba(255, 51, 85, .85);">Settings</a>
            <div class="dropdown-content">
              <a href="{% url 'accounts:edit_profile' %}">Edit Profile</a>
              <a href="{% url 'accounts:change_password' %}">Change Password</a>
            </div>
         </li> 
         <li><a href=" {% url 'accounts:logout' %}"> Logout</a></li>
        </ul>
      </nav>
    </header>
    <!-- header end -->

    <main role="main">

      <section class="alexa">
         <div class="container">
            <div class="row">
            <div class="col-md-6 text">
                <h1 class="jumbotron-heading"> Hi, <b>{{user.username}}</b> </h1>
                <p class="lead text-muted">Email: <b>{{ user.email }}</b></p>
                <p class="lead text-muted"> Progress: <b>{{ user.userprofile.progress }}</b></p>
            <div class="progress">
                <div class="progress-bar" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width:{{user.userprofile.progress}}%">
                <span class="sr-only">70% Complete</span>
                </div>
            </div>
            </div>
            </div>
         </div>

      <div class="section" id="projects">

        <div class="container">
            <!-- main container -->
            <div class="main-container portfolio-inner clearfix">
                <!-- portfolio div -->
                <div class="portfolio-div">
                    <div class="portfolio">                        
                        <!-- portfolio_container -->
                        <div class="no-padding portfolio_container clearfix">
                            <!-- single work -->
                            <div class="col-md-4 col-sm-6">
                                <a id="demo01" href="{% url 'accounts:rps' %}" class="portfolio_item"> 
                                    <center><img src="{% static 'accounts/profile/profile img/rps2.png' %}"  alt="Card image cap" class="img-responsive" style="height: 200px"></center>
                                    <div class="portfolio_item_hover">
                                        <div class="portfolio-border clearfix">
                                            <div class="item_info">
                                                <p>Rock, paper and scissors</p>
                                                <em>Rock, paper or scissor? Come on and create your own rock, paper and scissor game!</em>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <!-- end single work -->
                            
                            <!-- single work -->
                            <div class="col-md-4 col-sm-6 projects">
                                <a id="demo02" href="{% url 'accounts:calc' %}" class="portfolio_item"> 
                                    <center><img src="{% static 'accounts/profile/profile img/calc2.png' %}" alt="Card image cap" class="img-responsive" style="height: 200px"></center>
                                    <div class="portfolio_item_hover">
                                        <div class="portfolio-border clearfix">
                                            <div class="item_info">
                                                <p>Calculator</p>
                                                <em>Make your own calculator.</em>
                                            </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <!-- end single work -->
                            
                            <!-- single work -->
                            <div class="col-md-4 col-sm-6 projects">
                                <a id="demo03" href="{% url 'accounts:pyglatin' %}" class="portfolio_item"> <center><img src="{% static 'accounts/profile/profile img/pyg2.png' %}" alt="Card image cap" class="img-responsive" style="height: 200px"></center>
                                    <div class="portfolio_item_hover">
                                        <div class="portfolio-border research">
                                            <div class="item_info">
                                                <p>Pyglatin</p>
                                                <em>Ever wondered how to speak Pyglatin? Build your own english to pyglatin convertor!</em> </div>
                                        </div>
                                    </div>
                                </a>
                            </div>
                            <!-- end single work -->
                            


                        </div>
                        <!-- end portfolio_container -->
                    </div>
                    <!-- portfolio -->
                </div>
                <!-- end portfolio div -->
            </div>
            <!-- end main container -->
        </div>
    </div>
    <!-- ./projects -->
      
    </main>



    <!-- Bootstrap core JavaScript
    ================================================== -->
    <!-- Placed at the end of the document so the pages load faster -->
    <script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
    <script>window.jQuery || document.write('<script src="Bootstrap/assets/js/vendor/jquery.min.js"><\/script>')</script>
    <script src="Bootstrap/assets/js/vendor/popper.min.js"></script>
    <script src="Bootstrap/dist/js/bootstrap.min.js"></script>
    <script src="Bootstrap/assets/js/vendor/holder.min.js"></script>
    <script>
      Holder.addTheme('thumb', {
        bg: '#55595c',
        fg: '#eceeef',
        text: 'Thumbnail'
      });
    </script>
  </body>
</html>

TheGirlCode/accounts/templates/accounts/sign_up.html
<html>
    <head>
        <title> Sign up | The Girl Code</title>

        {% load static %}
        <link rel="stylesheet" href="{% static 'accounts/forms.css' %}" type="text/css">
        <link rel="icon" href="{% static 'TheGirlCode/LandingPage/Images/logo_trans.png' %}">

    </head>

    <body>

        <div class="container">
          <h1>Create Your Account</h1>
          <form method="post">
              {% csrf_token %}

              {{ form.as_p }}

              <center><button type="submit">Sign Up</button></center>
          </form>
        </div>

    </body>

</html>