TheGirlCode/TheGirlCode/urls.py
from django.conf.urls import url,include
from django.contrib import admin
from . import views

urlpatterns = [
    #Admin
    url(r'^admin/', admin.site.urls),

    #Home Page
    url(r'^$', views.home , name ='home'),

    #About Us
    url(r'^aboutus/$', views.about_us , name ='about_us'),

    #Workshops
    url(r'^workshops/$', views.workshops , name ='workshops'),

    # Accounts
    url(r'^account/', include('accounts.urls')),



]

TheGirlCode/accounts/urls.py
from django.conf.urls import url
from . import views
from django.contrib.auth.views import login, logout, password_reset, password_reset_done

app_name='accounts'
urlpatterns = [

    # Profile
    url(r'^profile/$', views.view_profile, name ='profile'),

    # Edit Profile Details
    url(r'^settings/edit/$', views.edit_profile, name ='edit_profile'),

    # Change Password
    url(r'^settings/edit/change_password$', views.change_password, name ='change_password'),

    # Login
    url(r'^login/$', login, {'template_name': 'accounts/login.html'}, name='login'),

    # Logout
    url(r'^logout/$', logout,  {'next_page': '/'}, name='logout'),

    # Register
    url(r'^register/$', views.register, name='register'),

    # Compiler
    url(r'^course/compiler/$', views.compiler, name='compiler'),

    # Curriculum 1
    url(r'^course-1/$', views.course_1, name='course1'),

    # Curriculum 2
    url(r'^course-2/$', views.course_2, name='course2'),

    # Curriculum 3
    url(r'^course-3/$', views.course_3, name='course3'),

    # Curriculum 4
    url(r'^course-4/$', views.course_4, name='course4'),

    # Curriculum 5
    url(r'^course-5/$', views.course_5, name='course5'),

    # Curriculum 6
    url(r'^course-6/$', views.course_6, name='course6'),

    # Curriculum 7
    url(r'^course-7/$', views.course_7, name='course7'),

    # Project 1
    url(r'^project-1/calculator$', views.calc, name='calc'),

    # Project 2
    url(r'^project-2/rps$', views.rps, name='rps'),

    # Project 3
    url(r'^project-3/pyglatin', views.pyglatin, name='pyglatin'),



]

TheGirlCode/accounts/models.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.db import models

from django.contrib.auth.models import User

from django.db.models.signals import post_save



class UserProfile(models.Model):
    user = models.OneToOneField(User, on_delete=models.CASCADE)   # Linking with the default django user model
    progress = models.IntegerField(default=0)  # Progress of the user

    answer_1_1 = models.CharField(max_length=50,default="")
    answer_1_1_check = models.BooleanField(default=False)

    answer_1_2 = models.IntegerField(default=0)
    answer_1_2_check = models.BooleanField(default=False)

    answer_1_3 = models.CharField(max_length=50,default="")
    answer_1_3_check = models.BooleanField(default=False)

    answer_1_4 = models.IntegerField(default=0)
    answer_1_4_check = models.BooleanField(default=False)

    answer_2_1 = models.CharField(max_length=50,default="")
    answer_2_1_check = models.BooleanField(default=False)

    answer_2_2= models.CharField(max_length=50,default="")
    answer_2_2_check = models.BooleanField(default=False)

    answer_2_3 = models.IntegerField(default=0)
    answer_2_3_check = models.BooleanField(default=False)

    answer_2_4 = models.CharField(max_length=50,default="")
    answer_2_4_check = models.BooleanField(default=False)

    answer_2_5 = models.CharField(max_length=50,default="")
    answer_2_5_check = models.BooleanField(default=False)

    answer_3_1 = models.CharField(max_length=50, default="")
    answer_3_1_check = models.BooleanField(default=False)

    answer_3_2 = models.CharField(max_length=50, default="")
    answer_3_2_check = models.BooleanField(default=False)

    answer_4_1 = models.IntegerField(default=0)
    answer_4_1_check = models.BooleanField(default=False)

    answer_4_2 = models.CharField(max_length=50, default="")
    answer_4_2_check = models.BooleanField(default=False)

    answer_4_3 = models.CharField(max_length=50, default="")
    answer_4_3_check = models.BooleanField(default=False)

    answer_5_1 = models.CharField(max_length=50, default="")
    answer_5_1_check = models.BooleanField(default=False)

    answer_6_1 = models.CharField(max_length=50, default="")
    answer_6_1_check = models.BooleanField(default=False)

    answer_6_2 = models.CharField(max_length=50, default="")
    answer_6_2_check = models.BooleanField(default=False)

    answer_6_3 = models.CharField(max_length=50, default="")
    answer_6_3_check = models.BooleanField(default=False)

    answer_7_1 = models.CharField(max_length=50, default="")
    answer_7_1_check = models.BooleanField(default=False)

    answer_7_2 = models.IntegerField(default=0)
    answer_7_2_check = models.BooleanField(default=False)

    def __str__(self):  # Displays names on the admin site
        return self.user.username


def create_profile(sender, **kwargs):  # Linking default User to UserProfile
    if kwargs['created']:
        user_profile = UserProfile.objects.create(user=kwargs['instance'])


post_save.connect(create_profile, sender=User)

TheGirlCode/accounts/forms.py
from django import forms
from django.forms import ModelForm
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm, UserChangeForm
from .models import UserProfile


class RegistrationForm(UserCreationForm):

    email = forms.EmailField(required=True)  # Valid email is mandatory

    class Meta:  # Description of the form
        model = User
        fields = (
            'username',
            'email',
            'password1',
            'password2'
        )

    def save(self, commit=True):  # Saves the data to the data base
        user = super(RegistrationForm, self ).save(commit=False)
        user.email = self.cleaned_data['email']  # Checks for code that can harm the site in the input box

        if commit:
            user.save()

        return user


class EditProfileForm(UserChangeForm):

    class Meta:  # Description of the form
        model = User
        fields = (
            'username',
            'email',
        )


class CourseForm1(forms.ModelForm):
    answer_1_1 = forms.CharField()
    answer_1_2 = forms.IntegerField()
    answer_1_3 = forms.CharField()
    answer_1_4 = forms.IntegerField()

    class Meta:
        model = UserProfile
        fields = ('answer_1_1','answer_1_2', 'answer_1_3', 'answer_1_4', )


class CourseForm2(forms.ModelForm):
    answer_2_1 = forms.CharField()
    answer_2_2 = forms.CharField()
    answer_2_3 = forms.IntegerField()
    answer_2_4 = forms.CharField()
    answer_2_5 = forms.CharField()


    class Meta:
        model = UserProfile
        fields = ('answer_2_1','answer_2_2', 'answer_2_3', 'answer_2_4', 'answer_2_5', )


class CourseForm3(forms.ModelForm):
    answer_3_1 = forms.CharField()
    answer_3_2 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_3_1','answer_3_2', )


class CourseForm4(forms.ModelForm):
    answer_4_1 = forms.IntegerField()
    answer_4_2 = forms.CharField()
    answer_4_3 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_4_1', 'answer_4_2', 'answer_4_3', )


class CourseForm5(forms.ModelForm):
    answer_5_1 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_5_1', )


class CourseForm6(forms.ModelForm):
    answer_6_1 = forms.CharField()
    answer_6_2 = forms.CharField()
    answer_6_3 = forms.CharField()

    class Meta:
        model = UserProfile
        fields = ('answer_6_1','answer_6_2','answer_6_3',  )


class CourseForm7(forms.ModelForm):
    answer_7_1 = forms.CharField()
    answer_7_2 = forms.IntegerField()

    class Meta:
        model = UserProfile
        fields = ('answer_7_1','answer_7_2',)

TheGirlCode/accounts/views.py
# -*- coding: utf-8 -*-
from __future__ import unicode_literals

from django.shortcuts import render, redirect, HttpResponse
from accounts.forms import *
from django.urls import reverse
from django.contrib.auth.forms import PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from .models import UserProfile


def login(request):

    return render(request, 'accounts/login.html')


def register(request):
    if request.method == 'POST':  # when submit button is clicked with the user details
        form = RegistrationForm(request.POST)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:login'))

    else:  # GET method, i.e. user is requesting the page
        form = RegistrationForm()

    return render(request, 'accounts/sign_up.html', {'form': form})


@login_required  # Page becomes inaccessible to users which are not logged in
def view_profile(request):

    return render(request, 'accounts/profile.html', {'user': request.user})


@login_required
def edit_profile(request):

    if request.method == 'POST':  # When user is submitting the updated info
        form = EditProfileForm(request.POST, instance=request.user)

        if form.is_valid():
            form.save()
            return redirect(reverse('accounts:profile'))

    else:  # When the user wants to view the page
        form = EditProfileForm(instance=request.user)

        return render(request, 'accounts/editprofile.html', {'form': form})
    

@login_required
def change_password(request):

    if request.method == 'POST':  # When user is submitting the updated info
        form = PasswordChangeForm(data=request.POST, user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)  # Doesn't logout the user after pw change
            return redirect(reverse('accounts:profile'))

        else:  # If form is not valid, redirects to the same page
            return redirect(reverse('accounts:change_password'))

    else:
        form = PasswordChangeForm(user=request.user)

        return render(request, 'accounts/changepassword.html', {'form': form})


def compiler(request):
    return render(request, 'accounts/compiler.html')


@login_required
def course_1(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm1(request.POST, instance=profile)
        if form.is_valid():
            ans1 = form.cleaned_data['answer_1_1']
            ans2 = form.cleaned_data['answer_1_2']
            ans3 = form.cleaned_data['answer_1_3']
            ans4 = form.cleaned_data['answer_1_4']

            if ans1 == "Hello World" and profile.answer_1_1_check == False:
                profile.progress += 5
                profile.answer_1_1_check = True
                profile.save()
            form.save()

            if ans2 == 2 and profile.answer_1_2_check == False:
                profile.progress += 5
                profile.answer_1_2_check = True
                profile.save()
            form.save()

            if ans3 == "True" and profile.answer_1_3_check == False:
                profile.progress += 5
                profile.answer_1_3_check = True
                profile.save()
            form.save()

            if ans4 == 1500 and profile.answer_1_4_check == False:
                profile.progress += 5
                profile.answer_1_4_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_1.html', args)

    else:
        form = CourseForm1(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_1.html', args)


def course_2(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm2(request.POST, instance=profile)
        if form.is_valid():
            ans5 = form.cleaned_data['answer_2_1']
            ans6 = form.cleaned_data['answer_2_2']
            ans7 = form.cleaned_data['answer_2_3']
            ans8 = form.cleaned_data['answer_2_4']
            ans9 = form.cleaned_data['answer_2_5']

            if ans5 == "JamandButter" and profile.answer_2_1_check == False:
                profile.progress += 5
                profile.answer_2_1_check = True
                profile.save()
            form.save()

            if ans6 == "actor" and profile.answer_2_2_check == False:
                profile.progress += 5
                profile.answer_2_2_check = True
                profile.save()
            form.save()

            if ans7 == 24 and profile.answer_2_3_check == False:
                profile.progress += 5
                profile.answer_2_3_check = True
                profile.save()
            form.save()

            if ans8 == "lang[1]" and profile.answer_2_4_check == False:
                profile.progress += 5
                profile.answer_2_4_check = True
                profile.save()
            form.save()

            if ans9 == "Hop" and profile.answer_2_5_check == False:
                profile.progress += 5
                profile.answer_2_5_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_2.html', args)

    else:
        form = CourseForm2(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_2.html', args)


def course_3(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm3(request.POST, instance=profile)
        if form.is_valid():
            ans10 = form.cleaned_data['answer_3_1']
            ans11 = form.cleaned_data['answer_3_2']

            if ans10 == "Your party was a success!" and profile.answer_3_1_check == False:
                profile.progress += 5
                profile.answer_3_1_check = True
                profile.save()
            form.save()

            if ans11 == "You are ancient." and profile.answer_3_2_check == False:
                profile.progress += 5
                profile.answer_3_2_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_3.html', args)

    else:
        form = CourseForm3(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_3.html', args)


def course_4(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm4(request.POST, instance=profile)
        if form.is_valid():
            ans12 = form.cleaned_data['answer_4_1']
            ans13 = form.cleaned_data['answer_4_2']
            ans14 = form.cleaned_data['answer_4_3']

            if ans12 == 10 and profile.answer_4_1_check == False:
                profile.progress += 5
                profile.answer_4_1_check = True
                profile.save()
            form.save()

            if ans13 == "1 2 3" and profile.answer_4_2_check == False:
                profile.progress += 5
                profile.answer_4_2_check = True
                profile.save()
            form.save()

            if ans14 == "odd even odd even" and profile.answer_4_3_check == False:
                profile.progress += 5
                profile.answer_4_3_check = True
                profile.save()
            form.save()

        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_4.html', args)

    else:
        form = CourseForm4(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_4.html', args)


def course_5(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm5(request.POST, instance=profile)
        if form.is_valid():
            ans15 = form.cleaned_data['answer_5_1']

            if ans15 == "eve.left(90)" and profile.answer_5_1_check == False:
                profile.progress += 5
                profile.answer_5_1_check = True
                profile.save()
            form.save()


        args = {'user': profile, 'form': form, }

        return render(request, 'accounts/course/course_5.html', args)

    else:
        form = CourseForm5(instance=profile)

        args = {'user': profile, 'form': form}
        return render(request, 'accounts/course/course_5.html', args)


def course_6(request):
    try:
        profile = request.user.userprofile
    except UserProfile.DoesNotExist:
        profile = UserProfile(user=request.user)

    if request.method == 'POST':
        form = CourseForm6(request.POST, instance=profile)
        if form.is_valid():
            ans16 = form.cleaned_data['answer_6_1']
            ans17 = form.cleaned_data['answer_6_2']
            ans18 = form.cleaned_data['answer_6_3']

            if ans16 == "butter" and profile.answer_6_1_check == False:
                profile.progress += 5
                profile.answer_6_1_check = True
                profile.save()
            form.save()

            if ans17 == "toffees chocolate" and profile.answer_6_2_check == False:

TheGirlCode/accounts/templates/accounts/course/course_3.html
{% extends 'accounts/course/course_base.html' %}

{% block title %} 3 {% endblock %}

{% block body %}

{% load static %}


      <div class="nine columns child">

        <div data-content="landing">

          <div class="question">

            <h1> Conditional Flow &middot; Python</h1>

            <p>

               <!-- laptop image -->
              <img src="{% static 'accounts/curriculum/Images/umbrellaeve.png' %}" align="right" width="30%"/> 
              <!-- laptop image end -->
              Is there anything worse than getting soaked in the cold rain? <br>

              Eve certainly doesn’t think so.<br> Should she take an umbrella with her when she leaves the house? The logical solution to Eve’s dilemma would be-<br> <br>


              if  it_is_raining :  <br> 
              &emsp;&emsp;
              carry_an_umbrella<br> 

              else:<br> 
              &emsp;&emsp;
              do_not_carry_an_umbrella 

              <br> 
              <br>

              Similarly, let's tackle another problem. If a child is older than 12, we usually refer to them as teenagers. Let’s create a program for that.<br><br>

              Take the user’s age as the input and save it in a variable <var> age </var>.
              <br> <br>

              <code> age = input("Enter age")</code>
              <br><br>
              If age is more than 12<br>
              &emsp;&emsp;
              print(“Welcome to the teen years!”) <br> <br>

              <ul> Here we can use conditions like:
              <li> == Equal to </li>
              <li>! = Not equal to </li>
              <li> > Greater than </li>
              <li> < Less than</li>
              </ul>

              <br>
              <p>

              So, <br> <br>

              <code> if age > 12 :</code> <br> <br>
              &emsp;&emsp;
              <code> print ("Welcome to the teen years!") </code>

                 <br> <br>

                **Note: A colon i.e. ' : ' has to be added after <b> every </b> if condition. If the colon is not placed after the condition, there will be a syntax error in your program.

                Also, the space on the second line is part of the Python Syntax.

                <br> <br>

                Syntax: <br> <br>

                <code> if <"some condition"> :</code> <br> <br>
                &emsp;&emsp;
                <code> action </code>

                <br><br>
                Want to know if you have enough chocolates or not? Simple! Set a condition. If you have more than 25 chocolates, you’re Willy Wonka!

                <br> <br>

                <!-- poc image -->
                <img src="{% static 'accounts/curriculum/Images/poc.png' %}" width="30%" align="right" /> 
               <!-- poc image end -->

                <code> Number_of_choc > 25: </code> <br> <br>
                &emsp;&emsp;
                <code>print("Greetings,Willy Wonka!")</code><br>

                <br> <br> 

                But wait..what if you wish to inform the user that they don't have enough chocolates? Well, you have <code> else</code> to the rescue!

                <br> <br>

                <code>if Number_of_choc > 25: </code> <br> <br>
                &emsp;&emsp;
                <code> print("Greetings,Willy Wonka!") </code> <br> <br>
                <code>else:</code> <br> <br>
                &emsp;&emsp;
                <code>print("Not everyone can be a Willy Wonka!")  </code> <br> <br>
                
                    
                Okay Willy Wonka, we have another situation at hand! You’re throwing a party for all your friends but, it’ll only be successful if there is an even number of guests so that  they can all be paired. If the guests are odd in number, one of them will be left out and your party will be a disaster :( <br> <br>

              <code>if ( number_of_people % 2 == 0): </code> <br> <br>
              &emsp;&emsp;
              <code>print("Good work! Your party was a success!")</code> <br> <br>
              <code> else:  </code> <br> <br>
              &emsp;&emsp;
              <code> print("One of your guests was alone.Failure!") </code> <br> <br>
            </p>
          </div>

          <h1> Questions &middot; Python</h1>

      <div class="question">
        <p> Answer by pasting the output in the box. </p>
        <form method="POST">
          <div class= "question">
            {% csrf_token %}

            <!-- QUESTION 1 -->
             <p>1. Output for<br>
              <code> if ( number_of_people % 2 == 0):</code><br>
              &emsp;&emsp;
              <code>print(“Your party was a success!”)</code><br>
              
              <code>else:</code><br>
              &emsp;&emsp;
              <code>print(“Party failed!")</code> <br><br>

              <p>Your party had 44 guests.</p><br>
             <br>
             {{ form.answer_3_1 }}
             <br>
             <br>
            <button type="submit"> Submit </button>
            <br>
            {% if  user.answer_3_1 == "Your party was a success!" %}
              <center> 
                <img src = "{% static 'accounts/curriculum/Images/happy.png' %}" height=200 width=250/> 
                <br> 
                <p> That's correct! </p>
              </center>
       
            {% else %}
              <center> 
                <img src = "{% static 'accounts/curriculum/Images/sad.png' %}" height=200 width=250/> 
                <br> 
                <p>Make me happy by answering correctly!</p>
              </center>
              <br>
              <br>
            {% endif %}
            <!-- QUESTION 1 END-->

            <!-- QUESTION 2 -->
            <p>2. Output of <br> <br>
            <code>if ( age == 1 or age < 1):</code><br>
            &emsp;&emsp;
            <code>print(“You’re a baby!”)</code><br>

            <code>else:</code><br>
            &emsp;&emsp;
            <code>print(“You are ancient.”)</code><br><br>

            age input is 3.

             <br><br>
             {{ form.answer_3_2 }}
             <br>
             <br>
            <button type="submit"> Submit </button>
            <br>
            {% if  user.answer_3_2 == "You are ancient." %}
              <center> 
                <img src = "{% static 'accounts/curriculum/Images/happy.png' %}" height=200 width=250/> 
                <br> <br>
                <p> That's correct! </p>
              </center>
       
            {% else %}
              <center> 
                <img src = "{% static 'accounts/curriculum/Images/sad.png' %}" height=200 width=250/> 
                <br> <br>
                <p>Make me happy by answering correctly!</p>
              </center>
              <br>
              <br>
            {% endif %}
            <!-- QUESTION 2 END -->

          </div>
        </form>  
      </div>
      <!-- Questions end -->





      </div>

{% endblock %}

TheGirlCode/accounts/templates/accounts/course/course_base.html
<!DOCTYPE html>

<head>

  <!-- Meta tags -->
  <meta charset="utf-8">
  <meta name="author" content="">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="theme-color" content="#2979ff">
  <!-- Meta tags end -->


  <!-- CSS Files -->
  {% load static %}
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/curriculum/skeleton.css'%}">
  <link rel="stylesheet" type="text/css" href="{% static 'accounts/curriculum/app.css'%}">

  <!-- CSS Files end -->

  <!-- bootstrap -->
  <link href="{% static 'Bootstrap/bootstrap.min.css' %}" rel="stylesheet">
  <link href="{% static 'Bootstrap/creative.min.css' %}" rel="stylesheet">
  <!-- bootstrap end -->

  <!-- stylesheet -->
  <link rel="stylesheet" href="{% static 'TheGirlCode/LandingPage/master.css' %}" media="screen" title="no title">
  <!-- stylesheet end -->

  <!-- Icons -->
  <link rel="stylesheet" type="text/css" href="http://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
  <link rel="apple-touch-icon-precomposed" href="img/icon.png">
  <link href="https://fonts.googleapis.com/css?family=Cardo|Inconsolata|Source+Sans+Pro" rel="stylesheet">
  <!-- Icons end-->

  <!-- Tab -->

  <title>Course {% block title %} 1 {% endblock %}| The Girl Code</title>
  <link rel="icon" href="{% static 'TheGirlCode/LandingPage/Images/logo_trans.png' %}">
  <!-- Tab end-->

</head>

<body>

    <!-- Navbar -->
    <header class="navbar-fixed-top light">
      <nav>
        <ul class="leftalign">
          <li><a style="color: rgba(255, 51, 85, .85)" href="{% url 'accounts:profile' %}">
              The Girl Code
             </a></li>
        </ul>
        <ul>
         <li><a href="{% url 'accounts:compiler' %}"> Compiler </a></li>
         <li><a href="{% url 'accounts:profile' %}"> Profile </a></li>
         <li><a href=" {% url 'accounts:logout' %}"> Logout</a></li>
        </ul>
      </nav>
    </header>
    <!-- Navbar end -->

  <div class="container">

    <div class="row">

      <div class="three columns child">

        <div class="rounds-list">
            <br>
        <a href="{% url 'accounts:course1' %}">
          <div class="list">
            <p>Basic Introduction</p>
          </div>
        </a>

        <a href="{% url 'accounts:course2' %}">
          <div class="list">
            <p>Strings</p>
          </div>
        </a>

        <a href="{% url 'accounts:course3' %}">
          <div class="list">
            <p>Conditional Flow</p>
          </div>
        </a>

        <a href="{% url 'accounts:course4' %}">
          <div class="list" >
            <p>Loops</p>
          </div>
        </a>

        <a href="{% url 'accounts:course5' %}">
          <div class="list">
            <p>Turtle Graphics</p>
          </div>
        </a>

        <a href="{% url 'accounts:course6' %}">
          <div class="list">
            <p>Lists</p>
          </div>
        </a>

        <a href="{% url 'accounts:course7' %}">
          <div class="list">
            <p>Functions </p>
          </div>
        </a>

        </div>

      </div>

        {% block body %}

        {% endblock %}



  <script src="//use.typekit.net/dbe5tbi.js"></script>
  <script>
    try {
      Typekit.load();
    } catch (e) {}
  </script>
  <script type="text/javascript" src="js/jquery-1.10.1.min.js"></script>
  <script type="text/x-mathjax-config">
    MathJax.Hub.Config({ tex2jax: {inlineMath: [['$','$'], ['\\(','\\)']]} });
  </script>

  <script type="text/javascript" src="//cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-AMS-MML_HTMLorMML">
  </script>

  <script type="text/javascript">
    $(".list").click(function() {
      $(this).find("ul").slideDown();
      $(this).find("i").css("display", "inline");
    });

    $(".list i").click(function(event) {
      event.stopPropagation();
      $(this).parent().find("ul").slideUp();
      $(this).css("display", "none");
    });

    $(".list ul li").click(function() {
      var difficulty = $(this).find("a").data("navigate");
      var roundCount = $(this).parent().parent().attr('id');
      $("div[data-content]").css("display", "none");
      $('div[data-content=' + roundCount + ']').css("display", "block");
      var id = '#' + difficulty;
      $('div[data-content=' + roundCount + ']').find('div[id]').css("display", "none");
      $('div[data-content=' + roundCount + ']').find(id).css("display", "block");
      if (roundCount == "round-one") {
        temp = "Round One &middot;";
      } else if (roundCount == "round-two") {
        temp = "Round Two &middot;";
      } else if (roundCount == "round-three") {
        temp = "Round Three &middot;";
      } else if (roundCount == "round-four") {
        temp = "Round Four &middot;";
      } else if (roundCount == "round-five") {
        temp = "Round Five &middot;";
      }
      var capitalized = difficulty[0].toUpperCase() + difficulty.substring(1);
      var newText = temp + ' ' + capitalized;
      $('div[data-content=' + roundCount + ']').find("h1").html(newText);
    });
  </script>

</body>

</html>